### PR TITLE
add indent support

### PR DESCRIPTION
**Pull request by shepherdwind**
support indent for velicity, indent key words if macro and foreach

### CODE REVIEW

**Comment by lepture** [comment]
don't write indent this way, try another way.

``` vim
if exists("b:did_indent")
  finish
endif

runtime! indent/html.vim

" write your code below
```

Just call the indent file `velocity.vim`

**Comment by lepture** [comment]
Hi, a good example: https://bitbucket.org/sjl/dotfiles/src/tip/vim/bundle/django-custom/indent/htmldjango.vim

**Comment by lepture** [comment]
by the way, I am using another html indent file, which is more efficient.

https://github.com/lepture/vim-javascript/blob/master/indent/html.vim

**Comment by shepherdwind** [comment]
ok, I will rewrite the indent file.

**Comment by shepherdwind** [comment]
Now, I write the indent/velocity file just the same way htmldjango.vim, thank you advice.

**Pull request merged**
